### ISSUE TITLE
Code highlight don't work when using "output" in `<py-script>` tag

### ISSUE THREAD

**Issue by Andrej123456789** [Hardeepsingh980/pyscript#3]
![image](https://user-images.githubusercontent.com/83548580/179205926-5147ee8d-c0b7-4fcd-a9dd-c3c68d0cc36d.png)

**Comment by Hardeepsingh980** [comment]
interesting, will look into it

**Comment by Andrej123456789** [comment]
Thanks for seeing issue, I hope it will be fixed soon

**Comment by Hardeepsingh980** [comment]
This issue is fixed and new version has been published to marketplace, you will see an update.

**Comment by Andrej123456789** [comment]
Thanks for fast issue resolving
